[package]
name = "fitgirl-decrypt"
version = "0.1.1"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.22.1"
bs58 = "0.5.1"
miniz_oxide = "0.8.8"
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ring = "0.17.14"

ureq = { version = "3.0.11", features = ["cookies", "json"] }
typenum = "1.18.0"
