[package]
name = "fitgirl-decryptor"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
fitgirl-decrypt = { workspace = true, features = ["nyquest"] }
nyquest-preset = { version = "0.1.0", features = ["async"] }
pollster = "0.4.0"
